remote: false
hybrid: true
onsite: true

experience_level:
  internship: false
  entry: true
  associate: true
  mid_senior_level: true
  director: false
  executive: false

job_types:
  full_time: true
  contract: false
  part_time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all_time: false
  month: false
  week: true
  24_hours: false

positions:
  - Business developer
  - Team Lead
  - Business development manager
  - Project manager
  - Strategy manager
  - Management consultant
  - Marketing manager
  - Coordinator
  - Growth manager
  - HR manager
  - Sales
  - Key Account Manager
  - PR manager
  - Brand manager
  - Commercial Coordinator
  - E-commerce manager
  - Commercial project manager

locations:
  - Copenhagen 
  - Copenhagen Municipality, Capital Region of Denmark, Denmark 
  - Copenhagen Metropolitan Area

apply_once_at_company: true

distance: 10

company_blacklist:
  - Netlight
  - Volvo Cars

title_blacklist:
  - Danish speaking
  - Remote
  - European Union (Remote)
  - European Economic Area (Remote)

location_blacklist:
  - Remote
  - Stockholm
  - Stockholm County, Sweden (On-site)
  - Stockholm County, Sweden (Hybrid)
  - Stockholm County, Sweden (Remote)
  - Stockholm County, Sweden
  - Stockholm, Stockholm County, Sweden (Hybrid)
  - Stockholm, Stockholm County, Sweden (Remote)
  - Stockholm, Stockholm County, Sweden (On-site)
  - Stockholm, Stockholm County, Sweden
  - Sweden (Remote)
  - Sweden
  - Sweden (On-site)
  - Greater Stockholm Metropolitan Area (Hybrid)
  - Greater Stockholm Metropolitan Area (On-site)
  - Greater Stockholm Metropolitan Area (Remote)
  - Greater Stockholm Metropolitan Area
  - Gothenburg
  - Göteborg
  - Malmö
  - Malmo
  - Malmoe
  - EMEA (Remote)
  - European Union (Remote)
  - European Economic Area (Remote)
  - Aarhus
  - Lund

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 10000

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'
